# This version is the golangci-lint version used to build the custom binary
version: v1.57.0

plugins:
  - module: "go.uber.org/nilaway"
    import: "go.uber.org/nilaway/cmd/gclplugin"
    version: latest  # or pin a tag/commit
