version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - nilaway
  settings:
    custom:
      nilaway:
        type: module
        description: Static analysis tool to detect potential nil panics in Go code.
        settings:
          # map[string]string, mimics CLI flags to NilAway:
          # include only your own packages to avoid going through all deps
          include-pkgs: "github.com/vitoruema/CeladonHotelPoc/..."

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
