// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lodging/ChatMessage.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Actor that produced the message.
type Sender int32

const (
	// Default zero value.
	Sender_SENDER_UNSPECIFIED Sender = 0
	// Guest-originated message.
	Sender_SENDER_GUEST Sender = 1
	// System-originated message.
	Sender_SENDER_SYSTEM Sender = 2
)

// Enum value maps for Sender.
var (
	Sender_name = map[int32]string{
		0: "SENDER_UNSPECIFIED",
		1: "SENDER_GUEST",
		2: "SENDER_SYSTEM",
	}
	Sender_value = map[string]int32{
		"SENDER_UNSPECIFIED": 0,
		"SENDER_GUEST":       1,
		"SENDER_SYSTEM":      2,
	}
)

func (x Sender) Enum() *Sender {
	p := new(Sender)
	*p = x
	return p
}

func (x Sender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sender) Descriptor() protoreflect.EnumDescriptor {
	return file_lodging_ChatMessage_proto_enumTypes[0].Descriptor()
}

func (Sender) Type() protoreflect.EnumType {
	return &file_lodging_ChatMessage_proto_enumTypes[0]
}

func (x Sender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sender.Descriptor instead.
func (Sender) EnumDescriptor() ([]byte, []int) {
	return file_lodging_ChatMessage_proto_rawDescGZIP(), []int{0}
}

// Acknowledgment outcome.
type AckStatus int32

const (
	// Default zero value.
	AckStatus_ACK_STATUS_UNSPECIFIED AckStatus = 0
	// Message accepted and processed.
	AckStatus_ACK_STATUS_ACCEPTED AckStatus = 1
	// Message rejected and not processed.
	AckStatus_ACK_STATUS_REJECTED AckStatus = 2
)

// Enum value maps for AckStatus.
var (
	AckStatus_name = map[int32]string{
		0: "ACK_STATUS_UNSPECIFIED",
		1: "ACK_STATUS_ACCEPTED",
		2: "ACK_STATUS_REJECTED",
	}
	AckStatus_value = map[string]int32{
		"ACK_STATUS_UNSPECIFIED": 0,
		"ACK_STATUS_ACCEPTED":    1,
		"ACK_STATUS_REJECTED":    2,
	}
)

func (x AckStatus) Enum() *AckStatus {
	p := new(AckStatus)
	*p = x
	return p
}

func (x AckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_lodging_ChatMessage_proto_enumTypes[1].Descriptor()
}

func (AckStatus) Type() protoreflect.EnumType {
	return &file_lodging_ChatMessage_proto_enumTypes[1]
}

func (x AckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckStatus.Descriptor instead.
func (AckStatus) EnumDescriptor() ([]byte, []int) {
	return file_lodging_ChatMessage_proto_rawDescGZIP(), []int{1}
}

// High-level lifecycle phase used for websocket flow validation.
type LifecyclePhase int32

const (
	// Default zero value.
	LifecyclePhase_LIFECYCLE_PHASE_UNSPECIFIED LifecyclePhase = 0
	// Guest is in check-in flow.
	LifecyclePhase_LIFECYCLE_PHASE_CHECK_IN LifecyclePhase = 1
	// Guest is checked in and currently staying.
	LifecyclePhase_LIFECYCLE_PHASE_STAY LifecyclePhase = 2
	// Guest is in checkout flow.
	LifecyclePhase_LIFECYCLE_PHASE_CHECK_OUT LifecyclePhase = 3
	// Stay is complete.
	LifecyclePhase_LIFECYCLE_PHASE_COMPLETED LifecyclePhase = 4
)

// Enum value maps for LifecyclePhase.
var (
	LifecyclePhase_name = map[int32]string{
		0: "LIFECYCLE_PHASE_UNSPECIFIED",
		1: "LIFECYCLE_PHASE_CHECK_IN",
		2: "LIFECYCLE_PHASE_STAY",
		3: "LIFECYCLE_PHASE_CHECK_OUT",
		4: "LIFECYCLE_PHASE_COMPLETED",
	}
	LifecyclePhase_value = map[string]int32{
		"LIFECYCLE_PHASE_UNSPECIFIED": 0,
		"LIFECYCLE_PHASE_CHECK_IN":    1,
		"LIFECYCLE_PHASE_STAY":        2,
		"LIFECYCLE_PHASE_CHECK_OUT":   3,
		"LIFECYCLE_PHASE_COMPLETED":   4,
	}
)

func (x LifecyclePhase) Enum() *LifecyclePhase {
	p := new(LifecyclePhase)
	*p = x
	return p
}

func (x LifecyclePhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LifecyclePhase) Descriptor() protoreflect.EnumDescriptor {
	return file_lodging_ChatMessage_proto_enumTypes[2].Descriptor()
}

func (LifecyclePhase) Type() protoreflect.EnumType {
	return &file_lodging_ChatMessage_proto_enumTypes[2]
}

func (x LifecyclePhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LifecyclePhase.Descriptor instead.
func (LifecyclePhase) EnumDescriptor() ([]byte, []int) {
	return file_lodging_ChatMessage_proto_rawDescGZIP(), []int{2}
}

// Stable machine-readable error codes for protocol and domain handling.
type ErrorCode int32

const (
	// Default zero value.
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0
	// No error / successful processing.
	ErrorCode_ERROR_CODE_NONE ErrorCode = 1
	// Message failed schema or required-field validation.
	ErrorCode_ERROR_CODE_VALIDATION_FAILED ErrorCode = 2
	// Message ordering or correlation is invalid.
	ErrorCode_ERROR_CODE_INVALID_STATE ErrorCode = 3
	// Requested entity was not found.
	ErrorCode_ERROR_CODE_NOT_FOUND ErrorCode = 4
	// Caller does not have permission for requested action.
	ErrorCode_ERROR_CODE_PERMISSION_DENIED ErrorCode = 5
	// Temporary system condition; safe to retry.
	ErrorCode_ERROR_CODE_TEMPORARY_UNAVAILABLE ErrorCode = 6
	// Unexpected internal failure.
	ErrorCode_ERROR_CODE_INTERNAL ErrorCode = 7
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_NONE",
		2: "ERROR_CODE_VALIDATION_FAILED",
		3: "ERROR_CODE_INVALID_STATE",
		4: "ERROR_CODE_NOT_FOUND",
		5: "ERROR_CODE_PERMISSION_DENIED",
		6: "ERROR_CODE_TEMPORARY_UNAVAILABLE",
		7: "ERROR_CODE_INTERNAL",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":           0,
		"ERROR_CODE_NONE":                  1,
		"ERROR_CODE_VALIDATION_FAILED":     2,
		"ERROR_CODE_INVALID_STATE":         3,
		"ERROR_CODE_NOT_FOUND":             4,
		"ERROR_CODE_PERMISSION_DENIED":     5,
		"ERROR_CODE_TEMPORARY_UNAVAILABLE": 6,
		"ERROR_CODE_INTERNAL":              7,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_lodging_ChatMessage_proto_enumTypes[3].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_lodging_ChatMessage_proto_enumTypes[3]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_lodging_ChatMessage_proto_rawDescGZIP(), []int{3}
}

// Transport envelope used for websocket exchange between guest and system.
type ChatMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ID for this message.
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Correlates request/response pairs across messages.
	CorrelationId string `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// UTC time at message creation.
	SentAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	// Originating actor.
	Sender Sender `protobuf:"varint,4,opt,name=sender,proto3,enum=lodging.v1.Sender" json:"sender,omitempty"`
	// Monotonic sequence per websocket session.
	Sequence uint64 `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Protocol contract version (for example: "lodging.v1").
	ProtocolVersion string `protobuf:"bytes,12,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Current interaction phase for message validation/routing.
	Phase LifecyclePhase `protobuf:"varint,13,opt,name=phase,proto3,enum=lodging.v1.LifecyclePhase" json:"phase,omitempty"`
	// Exactly one payload variant per envelope.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*ChatMessage_GuestAction
	//	*ChatMessage_GuestResponse
	//	*ChatMessage_SystemNotification
	//	*ChatMessage_SystemRequest
	//	*ChatMessage_Ack
	//	*ChatMessage_ErrorDetail
	Payload       isChatMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_lodging_ChatMessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_lodging_ChatMessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_lodging_ChatMessage_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatMessage) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ChatMessage) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *ChatMessage) GetSender() Sender {
	if x != nil {
		return x.Sender
	}
	return Sender_SENDER_UNSPECIFIED
}

func (x *ChatMessage) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ChatMessage) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *ChatMessage) GetPhase() LifecyclePhase {
	if x != nil {
		return x.Phase
	}
	return LifecyclePhase_LIFECYCLE_PHASE_UNSPECIFIED
}

func (x *ChatMessage) GetPayload() isChatMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChatMessage) GetGuestAction() GuestAction {
	if x != nil {
		if x, ok := x.Payload.(*ChatMessage_GuestAction); ok {
			return x.GuestAction
		}
	}
	return GuestAction_GUEST_ACTION_UNSPECIFIED
}

func (x *ChatMessage) GetGuestResponse() *GuestResponse {
	if x != nil {
		if x, ok := x.Payload.(*ChatMessage_GuestResponse); ok {
			return x.GuestResponse
		}
	}
	return nil
}

func (x *ChatMessage) GetSystemNotification() SystemNotification {
	if x != nil {
		if x, ok := x.Payload.(*ChatMessage_SystemNotification); ok {
			return x.SystemNotification
		}
	}
	return SystemNotification_SYSTEM_NOTIFICATION_UNSPECIFIED
}

func (x *ChatMessage) GetSystemRequest() SystemRequest {
	if x != nil {
		if x, ok := x.Payload.(*ChatMessage_SystemRequest); ok {
			return x.SystemRequest
		}
	}
	return SystemRequest_SYSTEM_REQUEST_UNSPECIFIED
}

func (x *ChatMessage) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Payload.(*ChatMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ChatMessage) GetErrorDetail() *ErrorDetail {
	if x != nil {
		if x, ok := x.Payload.(*ChatMessage_ErrorDetail); ok {
			return x.ErrorDetail
		}
	}
	return nil
}

type isChatMessage_Payload interface {
	isChatMessage_Payload()
}

type ChatMessage_GuestAction struct {
	// Guest-initiated lifecycle action.
	GuestAction GuestAction `protobuf:"varint,6,opt,name=guest_action,json=guestAction,proto3,enum=lodging.v1.GuestAction,oneof"`
}

type ChatMessage_GuestResponse struct {
	// Guest data/action response to a system request.
	GuestResponse *GuestResponse `protobuf:"bytes,7,opt,name=guest_response,json=guestResponse,proto3,oneof"`
}

type ChatMessage_SystemNotification struct {
	// Informational event emitted by the system.
	SystemNotification SystemNotification `protobuf:"varint,8,opt,name=system_notification,json=systemNotification,proto3,enum=lodging.v1.SystemNotification,oneof"`
}

type ChatMessage_SystemRequest struct {
	// Action/data request emitted by the system.
	SystemRequest SystemRequest `protobuf:"varint,9,opt,name=system_request,json=systemRequest,proto3,enum=lodging.v1.SystemRequest,oneof"`
}

type ChatMessage_Ack struct {
	// Delivery/processing acknowledgment for a prior message.
	Ack *Ack `protobuf:"bytes,10,opt,name=ack,proto3,oneof"`
}

type ChatMessage_ErrorDetail struct {
	// Structured protocol/domain error payload.
	ErrorDetail *ErrorDetail `protobuf:"bytes,11,opt,name=error_detail,json=errorDetail,proto3,oneof"`
}

func (*ChatMessage_GuestAction) isChatMessage_Payload() {}

func (*ChatMessage_GuestResponse) isChatMessage_Payload() {}

func (*ChatMessage_SystemNotification) isChatMessage_Payload() {}

func (*ChatMessage_SystemRequest) isChatMessage_Payload() {}

func (*ChatMessage_Ack) isChatMessage_Payload() {}

func (*ChatMessage_ErrorDetail) isChatMessage_Payload() {}

// Acknowledges a previously received message.
type Ack struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message ID being acknowledged.
	AcknowledgedMessageId string `protobuf:"bytes,1,opt,name=acknowledged_message_id,json=acknowledgedMessageId,proto3" json:"acknowledged_message_id,omitempty"`
	// Ack processing result.
	Status AckStatus `protobuf:"varint,2,opt,name=status,proto3,enum=lodging.v1.AckStatus" json:"status,omitempty"`
	// Machine-readable result code. Clients should branch on this value.
	Code ErrorCode `protobuf:"varint,3,opt,name=code,proto3,enum=lodging.v1.ErrorCode" json:"code,omitempty"`
	// Human-readable context for accepted/rejected handling.
	Reason        string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_lodging_ChatMessage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_lodging_ChatMessage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_lodging_ChatMessage_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetAcknowledgedMessageId() string {
	if x != nil {
		return x.AcknowledgedMessageId
	}
	return ""
}

func (x *Ack) GetStatus() AckStatus {
	if x != nil {
		return x.Status
	}
	return AckStatus_ACK_STATUS_UNSPECIFIED
}

func (x *Ack) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *Ack) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Structured error payload for machine handling and retries.
type ErrorDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Machine-readable error code. Clients should branch on this value.
	Code ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=lodging.v1.ErrorCode" json:"code,omitempty"`
	// Human-readable error message.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Indicates whether the operation can be retried safely.
	Retryable bool `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	// Optional implementation-specific details for diagnostics.
	Details       string `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_lodging_ChatMessage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_lodging_ChatMessage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_lodging_ChatMessage_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorDetail) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *ErrorDetail) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_lodging_ChatMessage_proto protoreflect.FileDescriptor

const file_lodging_ChatMessage_proto_rawDesc = "" +
	"\n" +
	"\x19lodging/ChatMessage.proto\x12\n" +
	"lodging.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13lodging/guest.proto\x1a\x14lodging/system.proto\"\xb4\x05\n" +
	"\vChatMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x123\n" +
	"\asent_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12*\n" +
	"\x06sender\x18\x04 \x01(\x0e2\x12.lodging.v1.SenderR\x06sender\x12\x1a\n" +
	"\bsequence\x18\x05 \x01(\x04R\bsequence\x12)\n" +
	"\x10protocol_version\x18\f \x01(\tR\x0fprotocolVersion\x120\n" +
	"\x05phase\x18\r \x01(\x0e2\x1a.lodging.v1.LifecyclePhaseR\x05phase\x12<\n" +
	"\fguest_action\x18\x06 \x01(\x0e2\x17.lodging.v1.GuestActionH\x00R\vguestAction\x12B\n" +
	"\x0eguest_response\x18\a \x01(\v2\x19.lodging.v1.GuestResponseH\x00R\rguestResponse\x12Q\n" +
	"\x13system_notification\x18\b \x01(\x0e2\x1e.lodging.v1.SystemNotificationH\x00R\x12systemNotification\x12B\n" +
	"\x0esystem_request\x18\t \x01(\x0e2\x19.lodging.v1.SystemRequestH\x00R\rsystemRequest\x12#\n" +
	"\x03ack\x18\n" +
	" \x01(\v2\x0f.lodging.v1.AckH\x00R\x03ack\x12<\n" +
	"\ferror_detail\x18\v \x01(\v2\x17.lodging.v1.ErrorDetailH\x00R\verrorDetailB\t\n" +
	"\apayload\"\xaf\x01\n" +
	"\x03Ack\x126\n" +
	"\x17acknowledged_message_id\x18\x01 \x01(\tR\x15acknowledgedMessageId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.lodging.v1.AckStatusR\x06status\x12)\n" +
	"\x04code\x18\x03 \x01(\x0e2\x15.lodging.v1.ErrorCodeR\x04code\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x8a\x01\n" +
	"\vErrorDetail\x12)\n" +
	"\x04code\x18\x01 \x01(\x0e2\x15.lodging.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x12\x18\n" +
	"\adetails\x18\x04 \x01(\tR\adetails*E\n" +
	"\x06Sender\x12\x16\n" +
	"\x12SENDER_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSENDER_GUEST\x10\x01\x12\x11\n" +
	"\rSENDER_SYSTEM\x10\x02*Y\n" +
	"\tAckStatus\x12\x1a\n" +
	"\x16ACK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ACK_STATUS_ACCEPTED\x10\x01\x12\x17\n" +
	"\x13ACK_STATUS_REJECTED\x10\x02*\xa7\x01\n" +
	"\x0eLifecyclePhase\x12\x1f\n" +
	"\x1bLIFECYCLE_PHASE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18LIFECYCLE_PHASE_CHECK_IN\x10\x01\x12\x18\n" +
	"\x14LIFECYCLE_PHASE_STAY\x10\x02\x12\x1d\n" +
	"\x19LIFECYCLE_PHASE_CHECK_OUT\x10\x03\x12\x1d\n" +
	"\x19LIFECYCLE_PHASE_COMPLETED\x10\x04*\xf7\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fERROR_CODE_NONE\x10\x01\x12 \n" +
	"\x1cERROR_CODE_VALIDATION_FAILED\x10\x02\x12\x1c\n" +
	"\x18ERROR_CODE_INVALID_STATE\x10\x03\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x04\x12 \n" +
	"\x1cERROR_CODE_PERMISSION_DENIED\x10\x05\x12$\n" +
	" ERROR_CODE_TEMPORARY_UNAVAILABLE\x10\x06\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\aB<Z:github.com/Kenji-Uema/guestManager/internal/domain/dto;dtob\x06proto3"

var (
	file_lodging_ChatMessage_proto_rawDescOnce sync.Once
	file_lodging_ChatMessage_proto_rawDescData []byte
)

func file_lodging_ChatMessage_proto_rawDescGZIP() []byte {
	file_lodging_ChatMessage_proto_rawDescOnce.Do(func() {
		file_lodging_ChatMessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lodging_ChatMessage_proto_rawDesc), len(file_lodging_ChatMessage_proto_rawDesc)))
	})
	return file_lodging_ChatMessage_proto_rawDescData
}

var file_lodging_ChatMessage_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_lodging_ChatMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_lodging_ChatMessage_proto_goTypes = []any{
	(Sender)(0),                   // 0: lodging.v1.Sender
	(AckStatus)(0),                // 1: lodging.v1.AckStatus
	(LifecyclePhase)(0),           // 2: lodging.v1.LifecyclePhase
	(ErrorCode)(0),                // 3: lodging.v1.ErrorCode
	(*ChatMessage)(nil),           // 4: lodging.v1.ChatMessage
	(*Ack)(nil),                   // 5: lodging.v1.Ack
	(*ErrorDetail)(nil),           // 6: lodging.v1.ErrorDetail
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(GuestAction)(0),              // 8: lodging.v1.GuestAction
	(*GuestResponse)(nil),         // 9: lodging.v1.GuestResponse
	(SystemNotification)(0),       // 10: lodging.v1.SystemNotification
	(SystemRequest)(0),            // 11: lodging.v1.SystemRequest
}
var file_lodging_ChatMessage_proto_depIdxs = []int32{
	7,  // 0: lodging.v1.ChatMessage.sent_at:type_name -> google.protobuf.Timestamp
	0,  // 1: lodging.v1.ChatMessage.sender:type_name -> lodging.v1.Sender
	2,  // 2: lodging.v1.ChatMessage.phase:type_name -> lodging.v1.LifecyclePhase
	8,  // 3: lodging.v1.ChatMessage.guest_action:type_name -> lodging.v1.GuestAction
	9,  // 4: lodging.v1.ChatMessage.guest_response:type_name -> lodging.v1.GuestResponse
	10, // 5: lodging.v1.ChatMessage.system_notification:type_name -> lodging.v1.SystemNotification
	11, // 6: lodging.v1.ChatMessage.system_request:type_name -> lodging.v1.SystemRequest
	5,  // 7: lodging.v1.ChatMessage.ack:type_name -> lodging.v1.Ack
	6,  // 8: lodging.v1.ChatMessage.error_detail:type_name -> lodging.v1.ErrorDetail
	1,  // 9: lodging.v1.Ack.status:type_name -> lodging.v1.AckStatus
	3,  // 10: lodging.v1.Ack.code:type_name -> lodging.v1.ErrorCode
	3,  // 11: lodging.v1.ErrorDetail.code:type_name -> lodging.v1.ErrorCode
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_lodging_ChatMessage_proto_init() }
func file_lodging_ChatMessage_proto_init() {
	if File_lodging_ChatMessage_proto != nil {
		return
	}
	file_lodging_guest_proto_init()
	file_lodging_system_proto_init()
	file_lodging_ChatMessage_proto_msgTypes[0].OneofWrappers = []any{
		(*ChatMessage_GuestAction)(nil),
		(*ChatMessage_GuestResponse)(nil),
		(*ChatMessage_SystemNotification)(nil),
		(*ChatMessage_SystemRequest)(nil),
		(*ChatMessage_Ack)(nil),
		(*ChatMessage_ErrorDetail)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lodging_ChatMessage_proto_rawDesc), len(file_lodging_ChatMessage_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lodging_ChatMessage_proto_goTypes,
		DependencyIndexes: file_lodging_ChatMessage_proto_depIdxs,
		EnumInfos:         file_lodging_ChatMessage_proto_enumTypes,
		MessageInfos:      file_lodging_ChatMessage_proto_msgTypes,
	}.Build()
	File_lodging_ChatMessage_proto = out.File
	file_lodging_ChatMessage_proto_goTypes = nil
	file_lodging_ChatMessage_proto_depIdxs = nil
}
